name: Build and Test on Commit

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trocar para a branch main
        run: |
          git fetch origin main
          git checkout main

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Instalar dependências
        run: mvn dependency:resolve

      - name: Compilar o projeto
        run: mvn clean compile -Dfile.encoding=UTF-8 -Dproject.build.sourceEncoding=UTF-8

      - name: Executar testes
        run: mvn test -Dfile.encoding=UTF-8 -Dproject.build.sourceEncoding=UTF-8
